### ISSUE TITLE
Update @actions/core to use the file version of save-state and set-output workflow commands

### ISSUE THREAD

**Issue by mazenkhalil** [aws-actions/setup-sam#59]
The below warning is initiated from `aws-actions/setup-sam@v2` step:
![image](https://user-images.githubusercontent.com/21160900/196657068-6e816433-ce3c-443f-9da1-47e9401c51a0.png)

This is due to the [depreciation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands) of `save-state` and `set-output` workflow commands.

Kindly update @actions/core to use the [file-command version](https://github.com/actions/toolkit/pull/1178) of `save-state` and `set-output` workflow commands. Thank you!

**Comment by hoffa** [comment]
Thanks for reporting this! I've updated `aws-actions/setup-sam@v2` with the newest version.
