### ISSUE TITLE
update Node.js 20

### ISSUE THREAD

**Issue by rivierch** [aws-actions/setup-sam#95]
![image](https://github.com/aws-actions/setup-sam/assets/56126645/7b0efbc0-13c1-43a1-a851-c9266775a1b7)

is it plan to update to Node.js 20 ?

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20

**Comment by GavinZZ** [comment]
Marking this issue as closed since the PR to update node runtime is completed and merged.
