### ISSUE TITLE
Add support for GitHub tokens

### ISSUE THREAD

**Issue by skyzyx** [aws-actions/setup-sam#98]
It would be helpful to add support for a `token` parameter so that we can more easily avoid GitHub rate limits.

**Comment by paulhcsun** [comment]
Hi @skyzyx, could you elaborate what the problem you're facing is how this would help fix it?

**Comment by skyzyx** [comment]
The GitHub.com rate limit is only 60 requests per hour for unauthenticated requests. It's 5,000 per hour for authenticated requests.

We're running inside GitHub Actions on GitHub Enterprise Server, and with the way that our CI nodes poke out through the corporate network, GitHub thinks all requests are coming from the same IP. As a result we burn through the unauthenticated rate limit quickly.

In `lib/setup.js` line 129 (I can't get the URL from the GitHub app on iPad… :/ ), the action makes a call to `api.github.com` in order to lookup the latest release (even though the rest of the package appears to install from PyPi).

The inability to specify a GitHub.com token means that we have many jobs using this action which fail. And our engineers have to wait (up to) an hour to try again.

**Comment by moelasmar** [comment]
sorry @skyzyx for late reply, I think yes we can add a new optional input for the action to get this token and use it while communicating with github apis. I will try to create a PR for this request soon.
